"""add recurring items

Revision ID: 8adb0528864c
Revises: 7d9c2a4e6b10
Create Date: 2026-08-04 11:21:16.387796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adb0528864c'
down_revision: Union[str, None] = '7d9c2a4e6b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=False),
    sa.Column('normalized_merchant', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('last_payment', sa.Date(), nullable=False),
    sa.Column('next_payment', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='suggested', nullable=False),
    sa.Column('confidence_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('price_change_percent', sa.Float(), server_default='0', nullable=False),
    sa.Column('price_change_warning', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_merchant', name='uq_recurring_item_user_merchant')
    )
    op.create_index(op.f('ix_recurring_items_frequency'), 'recurring_items', ['frequency'], unique=False)
    op.create_index(op.f('ix_recurring_items_next_payment'), 'recurring_items', ['next_payment'], unique=False)
    op.create_index(op.f('ix_recurring_items_normalized_merchant'), 'recurring_items', ['normalized_merchant'], unique=False)
    op.create_index(op.f('ix_recurring_items_status'), 'recurring_items', ['status'], unique=False)
    op.create_index(op.f('ix_recurring_items_user_id'), 'recurring_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_items_user_id'), table_name='recurring_items')
    op.drop_index(op.f('ix_recurring_items_status'), table_name='recurring_items')
    op.drop_index(op.f('ix_recurring_items_normalized_merchant'), table_name='recurring_items')
    op.drop_index(op.f('ix_recurring_items_next_payment'), table_name='recurring_items')
    op.drop_index(op.f('ix_recurring_items_frequency'), table_name='recurring_items')
    op.drop_table('recurring_items')
    # ### end Alembic commands ###
