"""add saved decisions

Revision ID: 9019a64f6fa2
Revises: 146ccae6e522
Create Date: 2026-08-08 23:35:26.753356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9019a64f6fa2'
down_revision: Union[str, None] = '146ccae6e522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('result_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_decisions_created_at'), 'saved_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_decisions_decision_type'), 'saved_decisions', ['decision_type'], unique=False)
    op.create_index(op.f('ix_saved_decisions_user_id'), 'saved_decisions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_decisions_user_id'), table_name='saved_decisions')
    op.drop_index(op.f('ix_saved_decisions_decision_type'), table_name='saved_decisions')
    op.drop_index(op.f('ix_saved_decisions_created_at'), table_name='saved_decisions')
    op.drop_table('saved_decisions')
    # ### end Alembic commands ###
