"""add plaid items and financial accounts

Revision ID: f77d39a9c4e0
Revises: 93dcf675c7ee
Create Date: 2026-07-30 10:49:16.091798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77d39a9c4e0'
down_revision: Union[str, None] = '93dcf675c7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_item_id', sa.String(length=255), nullable=False),
    sa.Column('institution_id', sa.String(length=255), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('access_token_ciphertext', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sync_cursor', sa.String(length=1024), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plaid_items_provider_item_id'), 'plaid_items', ['provider_item_id'], unique=True)
    op.create_index(op.f('ix_plaid_items_status'), 'plaid_items', ['status'], unique=False)
    op.create_index(op.f('ix_plaid_items_user_id'), 'plaid_items', ['user_id'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaid_item_id', sa.Integer(), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('official_name', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=64), nullable=False),
    sa.Column('account_subtype', sa.String(length=64), nullable=True),
    sa.Column('mask', sa.String(length=16), nullable=True),
    sa.Column('current_balance_cents', sa.Integer(), nullable=True),
    sa.Column('available_balance_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_accounts_account_type'), 'financial_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_financial_accounts_plaid_item_id'), 'financial_accounts', ['plaid_item_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_provider_account_id'), 'financial_accounts', ['provider_account_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_accounts_provider_account_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_plaid_item_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_account_type'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_plaid_items_user_id'), table_name='plaid_items')
    op.drop_index(op.f('ix_plaid_items_status'), table_name='plaid_items')
    op.drop_index(op.f('ix_plaid_items_provider_item_id'), table_name='plaid_items')
    op.drop_table('plaid_items')
    # ### end Alembic commands ###
